### ISSUE TITLE
Чёто нифига не работает

### ISSUE THREAD

**Issue by Flashwalker** [medvosa/cuda_css_inspector#11]
Не работает, показывает `?`

Requirement already satisfied: lxml in /usr/local/lib/python3.9/dist-packages (4.9.1)
Requirement already satisfied: cssselect in /usr/lib/python3/dist-packages (1.1.0)

**Comment by Alexey-T** [comment]
что именно вы делаете - по шагам, плиз.
что это за строки и как мне их увидеть?

**Comment by Alexey-T** [comment]
а, я догнал - у меня тоже показывает только ? при вызове в HTML. подумаю.

**Comment by Alexey-T** [comment]
найти причину пока трудно мне. сорри.

**Comment by CudaText-addons** [comment]
@Flashwalker обновил плагин (в Addons Manager), поправив 2-3 ошибки.
решено.
проверьте у вас.

**Comment by Flashwalker** [comment]
Да, помогло, спс

**Comment by Flashwalker** [comment]
Но работает так себе:
Тут не видит css из тега <style>:
![2022-07-29_21-23-35](https://user-images.githubusercontent.com/2188215/181822070-f0c0fdb3-6bbf-48e2-a871-76c1ddb5f1d6.png)

А тут видит всё сразу, хотя было б удобнее вычисленный css, но это видимо фича а не баг (но тогда не помешал бы скроллбар):
![2022-07-29_21-24-52](https://user-images.githubusercontent.com/2188215/181822425-ac94fb05-a92b-4600-8b84-f2722a8dc63d.png)

**Comment by Flashwalker** [comment]
Но работает так себе:
Тут не видит ни css из тега <style> ни из файла:
![2022-07-29_21-23-35](https://user-images.githubusercontent.com/2188215/181822070-f0c0fdb3-6bbf-48e2-a871-76c1ddb5f1d6.png)

А тут видит всё сразу, хотя было б удобнее вычисленный css, но это видимо фича а не баг (но тогда не помешал бы скроллбар):
![2022-07-29_21-24-52](https://user-images.githubusercontent.com/2188215/181822425-ac94fb05-a92b-4600-8b84-f2722a8dc63d.png)

http://0x0.st/ojhH.zip

**Comment by Alexey-T** [comment]
>(но тогда не помешал бы скроллбар):

сделал listbox - он имеет скроллбары. обновил в addon manager.

>отя было б удобнее вычисленный css, но это видимо фича а не баг

не знаю как работать с библиотекой (питона) и сделать "вычисленный". код основы писал не  я. я только мелочи поправил.

>Тут не видит ни css из тега <style> ни из файла:

на скрине видно что у одного class это .swiper-container, а у другого там еще что-то приписано после пробела. значит это разные классы?

**Comment by Flashwalker** [comment]
> на скрине видно что у одного class это .swiper-container, а у другого там еще что-то приписано после пробела. значит это разные классы?

После пробела это другие классы, но `.swiper-container` совпадает а значит должен отображаться.
Классы навешиваются на элемент через пробел. Ну и по идее все стили для каждого класса должны отображаться

**Comment by Alexey-T** [comment]
ясно...
плагин юзает вот эту либу-
https://pypi.org/project/cssselect/
(в Линуксе она должна быть последняя)
значит либа то ли не понимает классы через пробел, то ли мы ее как-то не так вызываем.
я не умею с ней работать.

 @veksha  Может вам интересно будет

**Comment by Alexey-T** [comment]
я понял как поправить про "пробелы в классе". вроде стало ОК на примере от @Flashwalker .
обновил.
окей?

**Comment by Flashwalker** [comment]
да, оно заработало

**Comment by Alexey-T** [comment]
спасибо за замечания.
да, родное репо теперь вот тут
https://github.com/CudaText-addons/cuda_css_inspector/issues
